[project]
name = "spine-conductor"
version = "0.1.dev"
description = "Release orchestration & automation scripts for Spine tools"
requires-python = ">=3.10"	# mostly for easier type hints
dependencies = ["gitpython", "packaging", "rich", "setuptools_scm", "tomlkit"]
